### ISSUE TITLE
SyntaxError 'username': username

### ISSUE THREAD

**Issue by Punten10** [Zlkcyber/pixelversexyz#3]
![image](https://github.com/Zlkcyber/pixelversexyz/assets/64400801/9b4806f7-0c5a-49f2-892b-faa68627dcba)

**Comment by hernycai** [comment]
same in macos
![Captura de Pantalla 2024-05-25 a la(s) 15 07 52](https://github.com/Zlkcyber/pixelversexyz/assets/139162326/7c97d1d3-a4d5-4dc0-97e3-4efa93aa22c2)

**Comment by lord-dubious** [comment]
it works

The issue in your code is a missing comma in the headers dictionary. This causes a syntax error. The comma is missing between 'user-agent' and 'username'.

**Comment by hernycai** [comment]
> it works
> 
> The issue in your code is a missing comma in the headers dictionary. This causes a syntax error. The comma is missing between 'user-agent' and 'username'.

new error

![Captura de Pantalla 2024-05-26 a la(s) 18 39 55](https://github.com/Zlkcyber/pixelversexyz/assets/139162326/df6948b8-57a5-45b4-bf35-b0b668fa1215)

**Comment by lord-dubious** [comment]
that means u didnt install all the required python packages, install the requirements.txt with ```` pip install requests````

**Comment by sitxxar** [comment]
> it works
> 
> The issue in your code is a missing comma in the headers dictionary. This causes a syntax error. The comma is missing between 'user-agent' and 'username'.

how to solve?

**Comment by sitxxar** [comment]
> it works
> 
> The issue in your code is a missing comma in the headers dictionary. This causes a syntax error. The comma is missing between 'user-agent' and 'username'.

event i try add coma, it still error like this 

![image](https://github.com/Zlkcyber/pixelversexyz/assets/37711440/64dccf44-3cd5-4acf-b4f0-373cde0f839f)

**Comment by Zlkcyber** [comment]
fixed
